services:
  database:
    image: postgres:14
    build: .//database
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Nawy2024
      - POSTGRES_DB=bookstore

    volumes:
      - bookstore-data:/var/lib/postgresql/data
    ports:
      - '5450:5432'

  app:
    build: .
    container_name: app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Nawy2024
      - POSTGRES_DB=bookstore
    ports:
      - 8080:8080
    links:
      - database
    depends_on:
      - database

volumes:
  database:
    driver: local
  bookstore-data:
